config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  root 'events#index'

  resources :events

  namespace :admin do
    root 'events#index'

    resources :events do
      collection do
        get 'pending'
      end

      member do
        put 'approve'
        put 'reject'
      end
    end
  end
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  include AASM

  aasm column: 'state' do
    state :pending, initial: true
    state :approved
    state :rejected

    event :approve do
      transitions from: :pending, to: :approved
    end

    event :reject do
      transitions from: :pending, to: :rejected
    end

    event :renew do
      transitions from: :rejected, to: :pending
    end
  end

  def self.resolved
    Event.where(state: %i[approved rejected])
  end

  validates :title, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true

  belongs_to :author, class_name: 'User'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, dependent: :destroy, foreign_key: 'author_id', inverse_of: :author
end

app/controllers/admin/base_controller.rb
# frozen_string_literal: true

class Admin
  class BaseController < ApplicationController
    before_action :authenticate_admin!
  end
end

app/controllers/admin/events_controller.rb
# frozen_string_literal: true

class Admin
  class EventsController < Admin::BaseController
    before_action :find_event, except: %i[index pending]

    def index
      @events = Event.resolved.order(created_at: :desc).page(params[:page])
    end

    def edit
      @event = Event.find(params[:id])
    end

    def update
      @event = Event.find(params[:id])

      if @event.update(event_params)
        redirect_to admin_events_path, success: t(:was_edited)
      else
        render :edit
      end
    end

    def destroy
      @event = Event.find(params[:id])

      @event.destroy

      redirect_to admin_events_path, warning: t(:was_deleted)
    end

    def pending
      @events = Event.pending.order(created_at: :desc).page(params[:page])
    end

    def approve
      @event = Event.find(params[:id])

      @event.approve!

      redirect_to pending_admin_events_path, success: t(:was_approved)
    end

    def reject
      @event = Event.find(params[:id])

      @event.reject!

      redirect_to pending_admin_events_path, warning: t(:was_rejected)
    end

    private

    def find_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit!
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  add_flash_types :success, :danger, :warning

  before_action :update_allowed_parameters, if: :devise_controller?

  helper_method :current_user

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name last_name email password])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name last_name email password current_password])
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :find_event, only: %i[show edit update destroy]
  before_action :check_user, only: %i[edit update destroy]

  def index
    @events = Event.approved.order(created_at: :desc).page(params[:page])
  end

  def show; end

  def new
    @event = Event.new
  end

  def create
    @event = EventCreator.call(event_params, current_user)

    if @event.save
      redirect_to events_path, success: t(:was_created)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @event.update(event_params)
      redirect_to events_path, success: t(:was_edited)
    else
      render :edit
    end
  end

  def destroy
    @event.destroy

    redirect_to events_path, warning: t(:was_deleted)
  end

  private

  def event_params
    params.require(:event).permit :title,
                                  :description,
                                  :location,
                                  :start_time,
                                  :end_time,
                                  :organizer_email,
                                  :organizer_telegram,
                                  :link
  end

  def find_event
    @event = Event.find(params[:id])
  end

  def check_user
    return if @event.author == current_user

    redirect_to events_path, warning: t(:no_rights)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/admin/events/_header.html.haml
.text-center= t(:admin_panel)
- if current_admin
  .container
    .font-italic= t(:logged_as_admin)
    .font-weight-bold #{current_admin.email}
    = link_to t(:sign_out_admin), destroy_admin_session_path, method: :delete, class: "btn btn-link"
%br
%br

app/views/admin/events/edit.html.haml
.container
  %h4
    = t(:edit_event)
    = simple_form_for [:admin, @event] do |f|
      = f.input :title, error: t(:title_necessary)
      = f.input :description
      = f.input :location
      = f.input :organizer_telegram
      = f.input :organizer_email
      = f.input :start_time
      = f.input :end_time
      = f.button :submit
      = link_to t(:cancel), admin_events_path, {:class=>"btn btn-default"}

app/views/admin/events/index.html.haml
.text-center= t(:admin_panel)
- if current_admin
  .container
    .font-italic= "#{t(:logged_as_admin)}"
    .font-weight-bold #{current_admin.email}
    = link_to t(:sign_out_admin), destroy_admin_session_path, method: :delete, class: "btn btn-link"
%br
%br
.container
  %ul.list-group
    - @events.each do |event|
      %li.list-group-item.d-flex.justify-content-between.align-items-center
        .d-flex.flex-column
          = event.title
          .small= event.description
          .small #{event.author.name} #{event.author.last_name}
        .btn-group
          = link_to t(:edit), edit_admin_event_path(event), class: "btn btn-outline-primary"
          = link_to t(:delete), admin_event_path(event), class: "btn btn-outline-danger", method: :delete, data: { confirm: t(:delete_confirm) }
    %br
    = paginate @events

app/views/admin/events/pending.html.haml
= render 'header'
.container
  %h3= t(:pending_events)
  %ul.list-group
    - @events.each do |event|
      %li.list-group-item.d-flex.justify-content-between.align-items-center
        .d-flex.flex-column
          = event.title
          .small= event.description
          .small #{event.author.name} #{event.author.last_name}
        .btn-group
          = link_to t(:approve), approve_admin_event_path(event), class: "btn btn-outline-success", method: :put
          = link_to t(:reject), reject_admin_event_path(event), class: "btn btn-outline-warning", method: :put
          = link_to t(:edit), edit_admin_event_path(event), class: "btn btn-outline-primary"
          = link_to t(:delete), admin_event_path(event), class: "btn btn-outline-danger", method: :delete, data: { confirm: t(:delete_confirm) }
    %br
    = paginate @events

app/views/events/_form.html.haml
= simple_form_for @event do |f|
  = f.input :title, error: t(:title_necessary)
  = f.input :description
  = f.input :location
  = f.input :organizer_telegram
  = f.input :organizer_email
  = f.input :start_time
  = f.input :end_time
  = f.button :submit
  = link_to t(:cancel), events_path, {:class=>"btn btn-default"}

app/views/events/edit.html.haml
.container
  %h1= t(:edit_event)
  = render "form", event: @event

app/views/events/index.html.haml
.text-center.jumbotron
  %h1= t(:events)
- if current_user
  .container
    .font-italic= "#{t(:logged_as)}"
    .font-weight-bold #{current_user.name} #{current_user.last_name} - #{current_user.email}
    = link_to t(:sign_out), destroy_user_session_path, method: :delete, class: "btn btn-link"
- if !current_user
  .container
    = link_to t(:sign_in), user_session_path, class: "btn btn-primary"
    = link_to t(:sign_up), new_user_registration_path, class: "btn btn-info"
%br
%br
.container
  %ul.list-group
    - @events.each do |event|
      %li.list-group-item.d-flex.justify-content-between.align-items-center
        .d-flex.flex-column
          = event.title
          .small= event.description
          .small #{event.author.name} #{event.author.last_name}
        .btn-group
          = link_to t(:view), event_path(event), class: "btn btn-outline-primary"
          = link_to t(:edit), edit_event_path(event), class: "btn btn-outline-primary" if event.author == current_user
          = link_to t(:delete), event_path(event), class: "btn btn-outline-danger", method: :delete, data: { confirm: t(:delete_confirm) } if event.author == current_user
    %br
    = paginate @events
  %br
  - if current_user
    %a.btn.btn-primary{ href: new_event_path() }= t(:new_event)

app/views/events/new.html.haml
.container
  %h1= t(:new_event)
  = render "form", event: @event

app/views/events/show.html.haml
.container
  %h1= @event.title
  %h4= @event.location
  .h6 #{t(:creator)}: #{@event.author.name} #{@event.author.last_name}
  %br
  #desc= @event.description
  %br
  - unless @event.organizer_email.empty?
    %blockquote #{t(:email)} #{@event.organizer_email}
  - unless @event.organizer_telegram.empty?
    %blockquote #{t(:telegram)} #{@event.organizer_telegram}
  %div
    %samp= @event.start_time.strftime("%d/%m/%Y - %H:%M")
  %div
    %samp= @event.end_time.strftime("%d/%m/%Y - %H:%M")

  %br
  = link_to t(:back), events_path, {:class=>"btn btn-light"}

app/views/layouts/admin.html.haml
= yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MkdevApp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - flash.each do |type, value|
      .alert.fade.show{ :class => "alert-#{type}" }
        %button.close{ :data => { :dismiss => "alert" } } x
        = value
    = yield